# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'capybara/rspec'
require 'selenium-webdriver'
require 'rspec/repeat'
require 'webdrivers'

Capybara.run_server = false
Capybara.default_max_wait_time = 10
Capybara.configure do |config|
  config.match = :prefer_exact
end

RSpec.configure do |config|
  config.include Capybara::DSL
  config.include RSpec::Repeat
  config.order = 'default' # Run specs in default order
  config.expect_with :rspec do |c| # Allow should syntax, which is now deprecated in rspec3
    c.syntax = [:should, :expect]
  end
  config.around(:each) do |example|
    repeat example, 3.times, :verbose => true
  end
end

Capybara.default_driver = :selenium_chrome
